# 📘 Introduction to NumPy

## 🔢 What is NumPy?

NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides:

    A powerful N-dimensional array object.

    Tools for integrating C/C++ and Fortran code.

    Useful linear algebra, Fourier transform, and random number capabilities.

## ✅ Why Use NumPy?

    Faster and more memory-efficient than Python lists.

    Offers vectorization: operations on whole arrays without Python loops.

    Ideal for data science, machine learning, image processing, and scientific computing.

| Feature       | Description                                                     |
| ------------- | --------------------------------------------------------------- |
| `ndarray`     | Efficient multi-dimensional array object                        |
| Broadcasting  | Perform arithmetic on arrays of different shapes                |
| Vectorization | Fast operations without loops                                   |
| Integration   | Easily integrates with C/C++, Fortran, pandas, matplotlib, etc. |


In [1]:
# Load libraries
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../../Numpy-GO/Dataset/CardioGoodFitness.csv')


In [3]:
df.sample(5).copy()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
126   TM498   34    Male         16     Partnered      3        4   59124   
72    TM195   39    Male         16     Partnered      4        4   59124   
52    TM195   29  Female         16     Partnered      4        3   50028   
64    TM195   35  Female         16     Partnered      3        3   60261   
176   TM798   42    Male         18        Single      5        4   89641   

     Miles  
126     85  
72     132  
52      94  
64      94  
176    200

In [4]:
arr = [1,2,3,5,42,5,16,51,61,2]
nparr = np.array(arr)
nparr

array([ 1,  2,  3,  5, 42,  5, 16, 51, 61,  2])

In [5]:
arr

[1, 2, 3, 5, 42, 5, 16, 51, 61, 2]

In [6]:
## checking Numpy Version
print(np.__version__)

1.26.4


In [7]:
# creating dimension array from normal array 
arr1 = np.array([1, 2, 3])          # 1D array
arr2 = np.array([[1, 2], [3, 4]])   # 2D array
arr2

array([[1, 2],
       [3, 4]])

In [8]:
# numpy array basics
# Create a 1D array

arr = [10,18,51,117,456,-14]
arr1 = np.array(arr)

# Create a 2D array
arr2 = np.array([[1, 2], [3, 4]])

# Check shape and type
print(arr1.shape)     # (6,)
print(f'shape of arr1:{arr1.shape}')
arr1.dtype
print(arr2.dtype)     # int64 (or int32 depending on system)
print(arr2.shape)


(6,)
shape of arr1:(6,)
int32
(2, 2)


In [9]:
np.zeros(5)                # [0. 0. 0. 0. 0.]
np.zeros((2, 3))           # 2x3 array of zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

### 📌 2. Creating Arrays from Python Lists or Tuples

In [10]:
arr1 = np.array([1, 2, 3])          # 1D array
arr2 = np.array([[1, 2], [3, 4]])   # 2D array

In [11]:
print(f"Array of arr1:{arr1}")
print(f"Array of arr2:{arr2}")

Array of arr1:[1 2 3]
Array of arr2:[[1 2]
 [3 4]]


### Creating Array with initial

In [12]:
############### zeros() ########################

# np.zeros(start,stop,num) 

zeros = np.zeros(5)
multi_zeros = np.zeros((3,2,5))
multi_zeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [13]:
####################### ones ############################
np.ones(4)                 # [1. 1. 1. 1.]
np.ones((3, 2))            # 3x2 array of ones


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
######################## Full ################################
np.full((2, 3), 70.2) 

array([[70.2, 70.2, 70.2],
       [70.2, 70.2, 70.2]])

### 📌 Creating Arrays with Ranges

In [18]:
np.arange(0, 10, 2)        # [0 2 4 6 8]


array([0, 2, 4, 6, 8])

In [19]:
np.linspace(0, 1, 5)       # [0.   0.25 0.5  0.75 1.  ]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 📌  Identity and Diagonal Matrices

In [24]:
np.eye(3)   # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.identity(4)   # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 📌  Random Arrays

In [29]:
np.random.rand(3)          # [0.12 0.84 0.33] (random)


array([0.32076108, 0.56941228, 0.04006536])

In [30]:
### with int value random array
np.random.randint(1, 10, size=(2, 3)) 

array([[4, 2, 3],
       [4, 1, 9]])

### 📌 Empty Array (uninitialized)

In [31]:
np.empty((2, 2))           # May contain random garbage values


array([[1., 1.],
       [1., 1.]])

### 📌  Reshape and Data Type

In [32]:
arr = np.arange(6)         # [0 1 2 3 4 5]
arr.reshape((2, 3))        # [[0 1 2]
                           #  [3 4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
np.array([1, 2, 3], dtype=float)   # [1. 2. 3.]


array([1., 2., 3.])

# 💡 Real-World Applications

  1.  Zeros and ones: For initializing weights in ML models.

  2.  arange, linspace: For time steps, mathematical functions, or graphing.
 
  3.  Random arrays: Simulating data, bootstrapping, training/testing splits.

  4.  reshape: Reformatting data for machine learning models.

# ✅ Summary Table
| Function                  | Description                  |
| ------------------------- | ---------------------------- |
| `np.array()`              | Create array from list/tuple |
| `np.zeros()`              | All elements zero            |
| `np.ones()`               | All elements one             |
| `np.full()`               | All elements custom value    |
| `np.arange()`             | Range with step              |
| `np.linspace()`           | Evenly spaced values         |
| `np.eye()` / `identity()` | Identity matrix              |
| `np.random.rand()`        | Random float numbers         |
| `np.random.randint()`     | Random integers              |
| `np.empty()`              | Uninitialized memory         |
| `reshape()`               | Change shape of array        |
