# Absulute Basics for Begineer

## How to import NumPy

Explanation about **How to import NumPy** goes here.

In [2]:
# Example code for: How to import NumPy
import numpy as np
import pandas as pd

## Reading the example code

Explanation about **Reading the example code** goes here.

In [3]:
# Example code for: Reading the example code
arr = np.array([10,-10,100])
print(arr)

[ 10 -10 100]


In [4]:
matrix = np.array([[1,0,0],[0,1,0],[0,0,1]])
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [6]:
matrix.ndim

2

## Why use NumPy?

Explanation about **Why use NumPy?** goes here.

Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

## What is an “array”?

Explanation about **What is an “array”?** goes here.

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data.
Most NumPy arrays have some restrictions. For instance:
1. All elements of the array must be of the same type of data.
2. Once created, the total size of the array can’t change.
3. The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

## Array fundamentals

Explanation about **Array fundamentals** goes here.

In [7]:
# Example code for: Array fundamentals
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
# indexing
a[:3]

array([1, 2, 3])

In [9]:
b = a[3:]
b

array([4, 5, 6])

In [10]:
b[0] = 40
a

array([ 1,  2,  3, 40,  5,  6])

In [13]:
mat_a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
mat_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# mat_a[row,column]
mat_a[1, 0]

5

## Array attributes

Explanation about **Array attributes** goes here.

In [ ]:
# Example code for: Array attributes

## How to create a basic array

Explanation about **How to create a basic array** goes here.

In [ ]:
# Example code for: How to create a basic array

## Adding, removing, and sorting elements

Explanation about **Adding, removing, and sorting elements** goes here.

In [ ]:
# Example code for: Adding, removing, and sorting elements

## How do you know the shape and size of an array?

Explanation about **How do you know the shape and size of an array?** goes here.

In [ ]:
# Example code for: How do you know the shape and size of an array?

## Can you reshape an array?

Explanation about **Can you reshape an array?** goes here.

In [ ]:
# Example code for: Can you reshape an array?

## How to convert a 1D array into a 2D array (how to add a new axis to an array)

Explanation about **How to convert a 1D array into a 2D array (how to add a new axis to an array)** goes here.

In [ ]:
# Example code for: How to convert a 1D array into a 2D array (how to add a new axis to an array)

## Indexing and slicing

Explanation about **Indexing and slicing** goes here.

In [ ]:
# Example code for: Indexing and slicing

## How to create an array from existing data

Explanation about **How to create an array from existing data** goes here.

In [ ]:
# Example code for: How to create an array from existing data

## Basic array operations

Explanation about **Basic array operations** goes here.

In [ ]:
# Example code for: Basic array operations

## Broadcasting

Explanation about **Broadcasting** goes here.

In [ ]:
# Example code for: Broadcasting

## More useful array operations

Explanation about **More useful array operations** goes here.

In [ ]:
# Example code for: More useful array operations

## Creating matrices

Explanation about **Creating matrices** goes here.

In [ ]:
# Example code for: Creating matrices

## Generating random numbers

Explanation about **Generating random numbers** goes here.

In [ ]:
# Example code for: Generating random numbers

## How to get unique items and counts

Explanation about **How to get unique items and counts** goes here.

In [ ]:
# Example code for: How to get unique items and counts

## Transposing and reshaping a matrix

Explanation about **Transposing and reshaping a matrix** goes here.

In [ ]:
# Example code for: Transposing and reshaping a matrix

## How to reverse an array

Explanation about **How to reverse an array** goes here.

In [ ]:
# Example code for: How to reverse an array

## Reshaping and flattening multidimensional arrays

Explanation about **Reshaping and flattening multidimensional arrays** goes here.

In [ ]:
# Example code for: Reshaping and flattening multidimensional arrays

## How to access the docstring for more information

Explanation about **How to access the docstring for more information** goes here.

In [ ]:
# Example code for: How to access the docstring for more information

## Working with mathematical formulas

Explanation about **Working with mathematical formulas** goes here.

In [ ]:
# Example code for: Working with mathematical formulas

## How to save and load NumPy objects

Explanation about **How to save and load NumPy objects** goes here.

In [ ]:
# Example code for: How to save and load NumPy objects

## Importing and exporting a CSV

Explanation about **Importing and exporting a CSV** goes here.

In [ ]:
# Example code for: Importing and exporting a CSV

## Plotting arrays with Matplotlib

Explanation about **Plotting arrays with Matplotlib** goes here.

In [ ]:
# Example code for: Plotting arrays with Matplotlib